#!/bin/sh
#
# Install NodeJS from Srouce
#
# Copyright (c) 2011 Lanvige Jiang <lanvige@gmail.com>
#
## END

version="0.6.5"
src_path="~/src"

echo "The Nodejs $version installation/upgrade will be start"

echo "Please choose you action type"
echo "i: Install (full with user create and init script) "
echo "u: Upgrade (just upgrade the nodejs version)"

read type

$ sudo apt-get install build-essential libssl-dev git-core

# Download and Install
if [ ! -x "$src_path"]; then
	echo "Create ~/src to store nodejs source"
	mkdir ~/src
fi

# Remove if node src exist
if [ ! -x "$src_path/node"]; then
	echo "Remove the old src"
	rm -rf node
fi


cd $src_path

git clone --depth 1 git://github.com/joyent/node.git

git checkout v$version
./configure --prefix=/usr/local/node-$version
make -j2
sudo make install
sudo ln -s /usr/local/node-$version /usr/local/node

if [ $type -eq i ] ; then
	echo 'export PATH=$PATH:/usr/local/node/bin' >> ~/.bashrc
fi

source ~/.bashrc

echo Install NPM

sudo chown -R $USER /usr/local
curl http://npmjs.org/install.sh | sudo sh

