#!/bin/sh
#
# Install NodeJS
#
# Copyright (c) 2011 Lanvige Jiang <lanvige@gmail.com>
#
## END

sudo apt-get install python-software-properties 
sudo add-apt-repository ppa:jerome-etienne/neoip 
sudo apt-get update
sudo apt-get install nodejs
